## 단어의 표현(Word Representation)

##### 기계는 문자를 그대로 인식할 수 없기 때문에 , 숫자로 변환

## 1 원-핫 인코딩( One-Hot Encoding)

##### 단어 집합 갯수 만큼

### 1.1 원숭이, 바나나, 사과 로 원-핫 인코딩 한다면

In [1]:
#인코딩 대상 단어들을 담은 리스트
word_ls=['원숭이','바나나','사과']

In [2]:
from collections import defaultdict
import numpy as np

def one_hot_encode(word_ls):
    #고유 단어와 인덱스를 매칭시켜 주는 사전 생성
    word2idx_dic = defaultdict(lambda:len(word2idx_dic))
    
    # {단어 : 인덱스 } 사전 구축
    for word in word_ls :
        word2idx_dic[word]
        
    #유니크한 단어 갯수 세는 변수.    
    n_unique_words=len(word2idx_dic) #고유한 단어의 갯수
    one_hot_vectors=np.zeros((len(word_ls),n_unique_words))#원핫-벡터를 만들기 위해 비어놓는다.
                    #np. zeros : 두 개의 인자 -> 2차원 배열
                     #np.zeros (차원 선언, dtype선언)  
    
    for i,word in enumerate(word_ls):
        index=word2idx_dic[word] #해당 단어의 고유 인덱스
        one_hot_vectors[i,index] +=1 #해당 단어의 고유 인덱스에만 1을 더해줌
        
    return one_hot_vectors
    

In [9]:
len(word_ls)

3

In [3]:
one_hot_vectors = one_hot_encode(word_ls)
one_hot_vectors

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
from collections import defaultdict
word2idx_dic = defaultdict(lambda:len(word2idx_dic))
word2idx_dic

defaultdict(<function __main__.<lambda>()>, {})

In [6]:
word2idx_dic['a']

0

In [7]:
word2idx_dic['b']

1

### 1.2 "코끼리"라는 단어가 추가된다면?

In [12]:
word_ls=['원숭이','바나나','사과','코끼리']

In [13]:
one_hot_vectors = one_hot_encode(word_ls)
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 1.3 sklearn을 활용한 one-hot encoding

In [18]:
#sklearn 을 활용한 one-hot encoding
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

#예제 데이터 배열
values= array(word_ls)
print(values)

#문자열에 숫자를 붙임
label_enc = LabelEncoder()
int_enc = label_enc.fit_transform(values)
print(int_enc)

#binary encode
onehot_enc = OneHotEncoder(sparse=False)
int_enc = int_enc.reshape(len(int_enc),1) #n:1 matrix로 변환
print(int_enc)
onehot_enc = onehot_enc.fit_transform(int_enc)
print(onehot_enc)

#인덱스 값을 넣었을 때, 키값? 벨류 값 출력

#one-hot encoding 의 첫번째 배열을 값을 역으로 산출
inverted = label_enc.inverse_transform([argmax(onehot_enc[0,:])])
print(inverted)

#argmax : 인자들 중 가장 큰 값 산출/출력
#인덱스 0 0 1   은 2이므로, 원숭이 출력

['원숭이' '바나나' '사과' '코끼리']
[2 0 1 3]
[[2]
 [0]
 [1]
 [3]]
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
['원숭이']


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [16]:
?LabelEncoder