In [3]:
from sklearn import datasets

In [14]:
iris=datasets.load_iris()

In [15]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [30]:
import pandas as pd
import numpy as np

In [31]:
from sklearn.model_selection import train_test_split

In [50]:
X=pd.DataFrame(iris['data'],columns =iris['feature_names'])
y=(iris['target']==2)

In [44]:
X_train,y_train ,X_test,y_test=train_test_split(X,y, test_size=0.2)

In [45]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

##### test size 로, x train, ytrain ,x test, ytest 를 나눠서 넣는다.

In [55]:
model=LogisticRegression()

##### model이라는 이름으로, LogisticRegression() 클래스에서 변수를 만든다.    fit를 해서, 임의의 값들이 들어가도록 해준다.

In [56]:
model.fit(X_train, y_train 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

##### predict :  값을 대신 예측해주는 것이다.

In [57]:
model.predict_proba(X_test)

array([[9.99823946e-01, 1.76054393e-04],
       [2.28638400e-01, 7.71361600e-01],
       [4.47045047e-01, 5.52954953e-01],
       [8.94566092e-01, 1.05433908e-01],
       [3.72448756e-01, 6.27551244e-01],
       [9.99992765e-01, 7.23534074e-06],
       [9.99920702e-01, 7.92975257e-05],
       [1.80389648e-01, 8.19610352e-01],
       [9.40643648e-01, 5.93563521e-02],
       [9.99931853e-01, 6.81465318e-05],
       [9.99969912e-01, 3.00884753e-05],
       [8.47719083e-01, 1.52280917e-01],
       [9.18445394e-01, 8.15546057e-02],
       [9.99987666e-01, 1.23338031e-05],
       [9.99967592e-01, 3.24078300e-05],
       [9.41104050e-01, 5.88959497e-02],
       [9.99967972e-01, 3.20281548e-05],
       [2.22786858e-01, 7.77213142e-01],
       [7.68092832e-01, 2.31907168e-01],
       [9.99911248e-01, 8.87523919e-05],
       [9.99961579e-01, 3.84213323e-05],
       [9.99931310e-01, 6.86901911e-05],
       [9.99967025e-01, 3.29749246e-05],
       [7.66521290e-01, 2.33478710e-01],
       [8.733344

In [62]:
X=iris['data'][:,(2,3)]

In [63]:
X=iris['data'][:,(2,3)]
y=iris['target']

In [73]:
softmax_reg=LogisticRegression(multi_class = 'multinomial'
                       ,solver='lbfgs')   # softmax을 푸는 solver??!!!!   어쩌구 저쩌구...
reg.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=1, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [74]:
from matplotlib import pyplot as plt

In [76]:
softmax_reg.fit(X,y)
softmax_reg.predict_proba([[5,2]])

array([[2.42794737e-04, 2.14966717e-01, 7.84790488e-01]])